server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: 'admin'
    password: 'admin'
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka